name: Build Windows EXE and Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install Inno Setup (ISCC)
      run: |
        choco install innosetup --yes

    - name: Restore credentials (secret)
      env:
        CLIENT_CONFIG: ${{ secrets.CLIENT_CONFIG_JSON }}
      run: |
        if ($env:CLIENT_CONFIG) {
          $clientPath = "resources\credentials\client_config.json"
          New-Item -ItemType Directory -Force -Path (Split-Path $clientPath)
          $env:CLIENT_CONFIG | Out-File -Encoding utf8 -FilePath $clientPath
        } else {
          Write-Error "CLIENT_CONFIG_JSON secret not set"
        }

    - name: Build with PyInstaller
      run: |
        # Diagnostic: show repository root contents so we can see whether the spec file exists
        Write-Host '=== Repo root files ==='
        Get-ChildItem -Force -File -Name | Sort-Object
        Write-Host '=== End repo root files ==='

        # Robust PyInstaller: use CalendarNow.spec if present, otherwise fall back to main.spec
        if (Test-Path 'CalendarNow.spec') {
          pyinstaller --noconfirm CalendarNow.spec
        } elseif (Test-Path 'main.spec') {
          Write-Host 'CalendarNow.spec not found; falling back to main.spec'
          pyinstaller --noconfirm main.spec
        } else {
          Write-Error "Spec file not found: CalendarNow.spec or main.spec"
        }

    - name: Compile installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" ".\installer\calendar-now.iss"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CalendarNow-Installer
        path: installer\Output\CalendarNow-Setup.exe
